version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/book_recommendation/db
volumes:
  mongodb_data_container:
  
