quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017
    database: book_recommendation
  http:
    port: 8081
  oidc:
    auth-server-url: http://0.0.0.0:8080/auth/realms/quarkus
    client-id: quarkus-service
    credentials:
      secret: admin
    tls:
      verification: none
    realm: quarkus
    keycloak:
      policy-enforcer:
        enable: true
      devservices:
        realm-path: quarkus